export const PRODUCTS = [
    {
      id: 1,
      productName: "Miabella Gold Over",
      price: 5153.00,
      //value:"gold",
      name:"gold",
      description:"High-Quality 14K Gold Plated. Lead-free, nickel-free, and hypoallergenic. It's very Skin-Friendly and suitable for daily wear",
      //title:"Gold",
      
      productImage:"https://m.media-amazon.com/images/I/71F9sJURfxL._AC_SY695_.jpg",
    },
    {
      id: 2,
      productName: "PAVOI Gold Chain Earrings",
      price: 1999.00,
      //value:"gold",
      name:"gold",
      //title:"Gold",
      description:"Simple design layered necklaces, you can wear each other as a single necklace or layering them all even match other necklaces which your favorite",
      productImage: "https://m.media-amazon.com/images/I/51wXe95cl+L._AC_SY695_.jpg"
     
    },
    {
      id: 3,
      productName: "Gold Plated Gold Earrings",
      price: 2345.00,
      //value:"gold",
      name:"gold",
      //title:"Gold",
      description:"As a piece of delicate jewelry, you can wrap it as a gift for someone you love, maybe your mom, your best friend, and so on. Of course, it is suitable for many occasions, such as weddings, beach, anniversaries, graduations, parties, proms, and more",
      productImage: "https://m.media-amazon.com/images/I/5191neqazNL._AC_SY695_.jpg",
     
    },
    {
      id: 4,
      productName: "Initial Necklaces Gold",
      price: 22805.00,
      //value:"gold",
      name:"gold",
      //title:"Gold",
      description:"We provide professional customer service, please send us your questions by email, and we will reply within 24 hours. Of course, we offer a 90-day No-Questions-Asked Refund. We wish you a perfect shopping experience",
      productImage:"https://m.media-amazon.com/images/I/51HavH8Uc7L._AC_SY695_.jpg",
    },
    {
      id: 5,
      productName: "TONLUYAX Gold Silver",
      price: 11999.00,
      //value:"silver",
      name:"gold",
      //title:"Silver",
      description:"Unique design: Chunky gold earrings with a teardrop design never go out of style. The classic shape and beautiful sheen make you stand out from the crowd.",
      productImage: "https://m.media-amazon.com/images/I/61Edaw21r+L._AC_SY695_.jpg",
     
    },
    {
      id: 6,
      productName: "PAVOI Gold Plated",
      price: 6998.0,
      //value:"silver",
      name:"gold",
      //title:"Silver",
      description:"Safe material: These trendy teardrop gold earrings are made of brass with 18k gold plated, and hypoallergenic material with 925 silver needles and does not flake off and lose color.",
      productImage:"https://m.media-amazon.com/images/I/61JVAyeKpHL._AC_SY695_.jpg",
      
    },
    {
      id: 7,
      productName: "PAVOI Gold Plated Rings",
      price: 12345,
      //value:"rose",
      name:"gold",
      //title:"Rose",
      description:"After sale service: Guarantee or money back, please feel free to contact us if the drop earring has any quality problems, free and easy return, and exchange.",
      productImage: "https://m.media-amazon.com/images/I/714Zfc8bgPL._AC_SY695_.jpg",
    },
    {
      id: 8,
      productName: "PAVOI Gold Plated",
      price: 40.012,
      //value:"rose",
      name:"gold",
      //title:"Rose",
      description:"Infinite Love:A wide variety of dainty Earrings,Necklace,Rings , no duplicate styles, super practical! You can wear different links no matter what the occasion",
      productImage: "https://m.media-amazon.com/images/I/51mGqEVTZYL._AC_SY695_.jpg",
    },
    {
    id: 9,
    productName: "PANSHI Sterling Silver Post Gold Drop Earrings",
    price: 143.00,
    //value:"rose",
    name:"silver",
    //title:"Rose",
    description:"NONNYL Pearl Services: All our necklace products arrive with a beautiful gift box, best for presentation and protection. If there is something wrong with our product, please just leave us a message, we strive to solve all the problems for you with high satisfaction!",
    productImage: "https://m.media-amazon.com/images/I/61TztnnxdXL._AC_SY695_.jpg",
  },
  {
    id: 10,
    productName: "Silver Bracelets for Women Teen Girls",
    price: 143.00,
    //value:"rose",
    name:"silver",
    //title:"Rose",
    description:"High Quality Material:CONGYING jewelry are made of high-quality alloy materials, using a unique gold-plated technology manufacturing, do their best to grow the life of the product and protect the appearance of durability, the appropriate weight, long time to wear will not produce a burden.",
    productImage: "https://m.media-amazon.com/images/I/51FBLOoQEiS._AC_SY695_.jpg",
  },
  {
  id: 11,
  productName: "Sterling Silver Bangle Bracelets",
  price: 1432.00,
  //value:"rose",
  name:"silver",
  //title:"Rose",
  description:"NONNYL Pearl Services: All our necklace products arrive with a beautiful gift box, best for presentation and protection. If there is something wrong with our product, please just leave us a message, we strive to solve all the problems for you with high satisfaction!",
  productImage: "https://m.media-amazon.com/images/I/415rNMoVRdL._AC_SY695_.jpg",
},
{
  id: 12,
  productName: "Teardrop Cluster Statement Necklace",
  price: 219.00,
  //value:"rose",
  name:"rose",
  //title:"Rose",
  description:"SUSTAINABILITY ✦ PAVOI is dedicated to sustainability throughout our entire product cycle. Our jewelry is made from 100% recycled materials and we package in 99% recycled materials. We work to reduce our carbon emissions and offset plastic consumption by removing 275,000 bottles from oceans annually. We are committed to maintain a balanced and eco-friendly business that minimizes our environmental impact. Trust that PAVOI is continuously working towards a greener future",
  productImage: "https://m.media-amazon.com/images/I/81G-xFCXo9L._AC_SY695_.jpg",
},
{
  id: 13,
  productName: "14k Rose Gold Princess",
  price: 2129.00,
  //value:"rose",
  name:"rose",
  //title:"Rose",
  description:"This Rose Gold Necklace is 18 Inches in Length with a 2 Inch Extension to Perfectly Fit all Neck Sizes. 14K Gold Plating Ensures a Long Lasting Finish That's Nickel Free, Lead Free, and Hypoallergenic.",
  productImage: "https://m.media-amazon.com/images/I/6137+GbXNKL._AC_SX695_.jpg",
},
{
  id: 14,
  productName: "Anniversary Bridal Wedding Ring",
  price: 219.00,
  //value:"rose",
  name:"rose",
  //title:"Rose",
  description:"[Perfect gift ideas] Excellent gift for your lover, girlfriend, daughter, mother, sister, wife. BONJOULRY Bangle bracelet makes a great gift fot Birthday, Wedding, Anniversary, Christmas",
  productImage: "https://m.media-amazon.com/images/I/81UQXmHsQZL._AC_SX679_.jpg",
},
{
  id: 15,
  productName: "Rhinestone Chandelier Bridal Earring",
  price: 219.00,
  //value:"rose",
  name:"rose",
  //title:"Rose",
  description:"Our Elastic bracelets measure 2.59 inches in inner diameter before stretching, 2.99 inches in outer diameter. Stretchable bracelets comfortably fit most size small to large wrists. Wide of our snake chain bracelet is 16MM",
  productImage: "https://m.media-amazon.com/images/I/71R93SKa2PL._AC_SX679_.jpg",
},
{
  id: 16,
  productName: "Stackable Ring Eternity Bands ",
  price: 4319.00,
  //value:"rose",
  name:"silver",
  //title:"Rose",
  description:"NONNYL Pearl Services: All our necklace products arrive with a beautiful gift box, best for presentation and protection. If there is something wrong with our product, please just leave us a message, we strive to solve all the problems for you with high satisfaction!",
  productImage: "https://m.media-amazon.com/images/I/61t6JF-TZRL._AC_SY695_.jpg",
},
{
  id: 17,
  productName: "Byzantine Bolo Bracelet",
  price: 679.00,
  //value:"rose",
  name:"rose",
  //title:"Rose",
  description:"We are committed to providing the best customer experience possible. If for any reason you are not fully satisfied with your purchase, we offer a hassle-free return and refund policy, ensuring your complete satisfaction and peace of mind.",
  productImage: "https://m.media-amazon.com/images/I/71zkCrNLANL._AC_SY695_.jpg",
},
{
  id: 18,
  productName: "Silver Chunky Hoop Earrings",
  price: 2679.00,
  //value:"rose",
  name:"silver",
  //title:"Rose",
  description:"Dainty Initial Necklaces Design: Are you looking for the perfect gift for someone special? Look no further than this timeless beautiful gold initial necklace.create lasting memories with personalized initial necklaces-choose your letter pendant choker necklace to represent your Love dreams and memories.",
  productImage: "https://m.media-amazon.com/images/I/510G5rgvlpL._AC_SY695_.jpg",
},
{
  id: 19,
  productName: "Tennis Necklace Bracelet",
  price: 779.00,
  //value:"rose",
  name:"silver",
  //title:"Rose",
  description:"Friendly Materials:Our initial necklace is made of hypoallergenic material brass and 14K gold plated to ensure the chain keeps tarnish-free, nickel free, lead-free, and hypoallergenic for a long time. Women with sensitive skin need not worry. It is suitable for all-day wear.",
  productImage: "https://m.media-amazon.com/images/I/61-7AaMiMoL._AC_SX679_.jpg",
},
{
  id: 20,
  productName: "Golden Cloud Gold Statement Earrings",
  price: 779.00,
  //value:"rose",
  name:"gold",
  //title:"Rose",
  description:"Foxgirl Warranty:We specialize in creating high-quality simple and trendy personalized jewelry that becomes part of your everyday life. If unsatisfied with the minimalist dainty initial necklace, please feel free to contact us.",
  productImage: "https://m.media-amazon.com/images/I/61ieXr2IfXS._AC_SY695_.jpg",
},

{
  id: 21,
  productName: "Layered Choker Necklace",
  price: 2779.00,
  //value:"rose",
  name:"rose",
  //title:"Rose",
  description:"Trustworthy Quality: Women necklace are made of 925 silver, it is a hypoallergenic silver heart necklace that is not easy to damage the skin. Gold plated necklaces for women are polished smooth for extra comfort.",
  productImage: "https://m.media-amazon.com/images/I/61CV7K7vjsL._AC_SY695_.jpg",
},
{
  id: 22,
  productName: "Diamond Choker Necklaces",
  price: 1569.00,
  //value:"rose",
  name:"silver",
  //title:"Rose",
  description:"NONNYL Pearl Services: All our necklace products arrive with a beautiful gift box, best for presentation and protection. If there is something wrong with our product, please just leave us a message, we strive to solve all the problems for you with high satisfaction!",
  productImage: "https://m.media-amazon.com/images/I/51CKyVRuW+L._AC_SX679_.jpg",
},
  ];